#!/usr/bin/env bash
# Opens a clearly-marked TEST proposal in iso24229/proposals to verify
# the end-to-end pipeline (form → issue → AG mirror → import PR).
#
# Requirements:
#   - gh CLI installed and authenticated with scope that can write to
#     iso24229/proposals
#   - The proposals repo + decisions repo must both have
#     ISO24229_CI_PAT_TOKEN set (you confirmed this).
#
# Usage:
#   ./scripts/test-proposal.sh                  # auto-generate test body
#   ./scripts/test-proposal.sh --label ready    # also label status:ready-for-AG
#                                               # (triggers the mirror workflow)
#   ./scripts/test-proposal.sh --clean ISSUE_NUMBER
#                                               # close + comment "TEST, please ignore"
#
# What this script does NOT do:
#   - Label the mirror issue in iso24229/decisions with status:AG-approved
#     (you do that manually so you can verify the import PR step)
#   - Clean up the resulting PR in iso24229/iso24229-register (you do that)

set -euo pipefail

REPO="iso24229/proposals"
TEST_TAG="[TEST — please ignore]"
TODAY=$(date -u +%Y-%m-%d)
NOW=$(date -u +%Y%m%d-%H%M%S)

# Sample proposal — Wade-Giles, which is a real historic Chinese
# romanization, so the schema validates, but flagged TEST so the AG
# knows to skip it. The substantive content matches what a real
# proposal would look like.

TITLE="$TEST_TAG [Proposal] ALA-LC Romanization Table -- Amharic (test $NOW)"

read -r -d '' BODY <<EOF || true
<!-- ISO 24229 system-code proposal generated by www.iso24229.org/about/apply/submit -->
<!-- integrity-sha256: 6f4a02b8c1a13e7b8d9c6e0a6e7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5 (test value) -->
<!-- TEST: this proposal exists only to verify the end-to-end pipeline. The AG should reject or ignore it. -->

### Your name

Pipeline Test Bot

### Organization (optional)

iso24229 tooling

### Your relationship to the proposed authority

I am proposing for the Varia authority (Var)

### Authority identifier

Var

### Authorization

I confirm I am authorized to submit on behalf of the chosen authority, OR I am proposing for Varia, OR I am proposing a new authority.

### Source language (ISO 639 code)

amh

### Source script (ISO 15924 code)

Ethi

### Source country (optional, ISO 3166-1 alpha-2)

ET

### Target script (ISO 15924 code)

Latn

### Identifying segment

test-$NOW

### System name (human-readable)

$TEST_TAG ALA-LC Romanization Table -- Amharic (test $NOW)

### Abstract

Pipeline verification entry. Not a real proposal. The Amharic test romanization is used purely to exercise the proposal→decision→register import workflow.

### Defining reference — title

Test Specification (not real)

### Defining reference — publisher

Pipeline Test Bot

### Defining reference — date

$TODAY

### Defining reference — URL (optional)

https://www.iso24229.org/about/apply

### Specification excerpt (optional)

_(not provided)_

### Demonstrative source 1

Title: Test Source 1
URL: https://example.org/test-1
Usage: This is a test source for pipeline verification only.

### Demonstrative source 2

Title: Test Source 2
URL: https://example.org/test-2
Usage: This is a test source for pipeline verification only.

### Demonstrative source 3

Title: Test Source 3
URL: https://example.org/test-3
Usage: This is a test source for pipeline verification only.

### Additional demonstrative sources (optional)

_(not provided)_

### Justification

This proposal exists only to verify the end-to-end pipeline. It should be rejected by the AG. No register entry should result.

### Example conversions

አማርኛ → amarəñña (test)
መጽሐፍ → mäs'ḥaf (test)

### Relations to other systems (optional)

_(not provided)_

### Submission terms

- [x] I confirm the information is accurate to the best of my knowledge
- [x] I understand the AG may reject this proposal, and that rejection does not result in a register entry
- [x] I understand this proposal is public, but the AG's deliberation (including voting) is private
- [x] I understand I will be @mentioned on this issue for any RA questions, and that I need GitHub notifications enabled to receive them

---

**TEST**: this proposal exists only to verify the proposal→decision→register import pipeline. Please label it \`status:ready-for-AG\` to exercise the mirror workflow, then label the corresponding mirror in \`iso24229/decisions\` \`status:AG-rejected\` to verify the rejection path (recommended over approval, which would actually create a register entry).
EOF

# ── Parse args ──────────────────────────────────────────────
ACTION="create"
LABEL_READY=false
CLEAN_ISSUE=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --label-ready|--ready) LABEL_READY=true; shift ;;
    --clean) ACTION="clean"; CLEAN_ISSUE="$2"; shift 2 ;;
    --help|-h)
      sed -n '2,30p' "$0"
      exit 0
      ;;
    *) echo "Unknown arg: $1" >&2; exit 1 ;;
  esac
done

# ── Verify gh auth ──────────────────────────────────────────
if ! gh auth status >/dev/null 2>&1; then
  echo "::error::gh CLI is not authenticated. Run 'gh auth login' first."
  exit 1
fi

if [[ "$ACTION" == "clean" ]]; then
  echo "→ Closing test issue #$CLEAN_ISSUE with cleanup comment"
  gh issue comment "$CLEAN_ISSUE" --repo "$REPO" \
    --body "Pipeline test complete. Closing. — Pipeline Test Bot"
  gh issue close "$CLEAN_ISSUE" --repo "$REPO" --reason "not planned"
  echo "✓ Issue #$CLEAN_ISSUE closed"
  exit 0
fi

# ── Create test issue ───────────────────────────────────────
echo "→ Opening test proposal in $REPO"
ISSUE_URL=$(gh issue create \
  --repo "$REPO" \
  --title "$TITLE" \
  --body "$BODY" \
  --label "type:system-proposal" \
  --label "status:received")

ISSUE_NUMBER=$(basename "$ISSUE_URL")
echo "✓ Opened: $ISSUE_URL"
echo "  Issue number: $ISSUE_NUMBER"
echo "  Title: $TITLE"

if $LABEL_READY; then
  echo "→ Adding status:ready-for-AG label (triggers mirror-to-decisions workflow)"
  gh issue edit "$ISSUE_NUMBER" --repo "$REPO" --add-label "status:ready-for-AG"
  echo "✓ Labelled. Mirror workflow should fire within ~30s."
  echo ""
  echo "Next steps to complete the test:"
  echo "  1. Watch the mirror workflow: https://github.com/$REPO/actions"
  echo "  2. Confirm a corresponding issue appears in iso24229/decisions"
  echo "  3. In decisions, label it status:AG-rejected (recommended over approved,"
  echo "     since approval would actually create a register entry)"
  echo "  4. Verify the rejection email/notification fires back on this proposal"
  echo "  5. Clean up: $0 --clean $ISSUE_NUMBER"
fi

echo ""
echo "Test proposal issue: $ISSUE_URL"
